name: examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang 
        run: |
          sudo apt install -y wget gnupg software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: make
        run: |
          make CC=clang
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  core:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run core examples
        run: |

  log:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run log example
        run: |
          chmod +x ${{github.workspace}}/build/examples/log_example
          ${{github.workspace}}/build/examples/log_example

  hash:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run hash example
        run: |
          chmod +x ${{github.workspace}}/build/examples/hash_example
          ${{github.workspace}}/build/examples/hash_example

  pack:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run pack example
        run: |
          chmod +x ${{github.workspace}}/build/examples/pack_example
          ${{github.workspace}}/build/examples/pack_example
  
  sync:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run sync example
        run: |
          chmod +x ${{github.workspace}}/build/examples/sync_example
          ${{github.workspace}}/build/examples/sync_example

  data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run data examples
        run: |

  array:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run array example
        run: |
          chmod +x ${{github.workspace}}/build/examples/array_example
          ${{github.workspace}}/build/examples/array_example
  
  circular_buffer:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run circular buffer example
        run: |
          chmod +x ${{github.workspace}}/build/examples/circular_buffer_example
          ${{github.workspace}}/build/examples/circular_buffer_example

  dict:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run dict example
        run: |
          chmod +x ${{github.workspace}}/build/examples/dict_example
          ${{github.workspace}}/build/examples/dict_example
  
  priority_queue:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run priority queue example
        run: |
          chmod +x ${{github.workspace}}/build/examples/priority_queue_example
          ${{github.workspace}}/build/examples/priority_queue_example
  
  queue:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run queue example
        run: |
          chmod +x ${{github.workspace}}/build/examples/queue_example
          ${{github.workspace}}/build/examples/queue_example
    
  stack:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run stack example
        run: |
          chmod +x ${{github.workspace}}/build/examples/stack_example
          ${{github.workspace}}/build/examples/stack_example
  
  tree:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run tree example
        run: |
          chmod +x ${{github.workspace}}/build/examples/tree_example
          ${{github.workspace}}/build/examples/tree_example
  
  tuple:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run tuple example
        run: |
          chmod +x ${{github.workspace}}/build/examples/tuple_example
          ${{github.workspace}}/build/examples/tuple_example
  
  reflection:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run reflection examples
        run: |

  base64:
    needs: reflection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run base64 example
        run: |
          chmod +x ${{github.workspace}}/build/examples/base64_example
          ${{github.workspace}}/build/examples/base64_example
  
  json:
    needs: reflection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run json example
        run: |
          chmod +x ${{github.workspace}}/build/examples/json_example
          ${{github.workspace}}/build/examples/json_example ${{github.workspace}}/resources/reflection/json_example_1.json