name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang 
        run: |
          sudo apt install -y wget gnupg software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: make
        run: |
          make CC=clang-20
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  core:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run core tests
        run: |

  pack:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run pack test
        run: |
          chmod +x ${{github.workspace}}/build/tests/pack_test
          ${{github.workspace}}/build/tests/pack_test
  
  hash:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run hash test
        run: |
          chmod +x ${{github.workspace}}/build/tests/hash_test
          ${{github.workspace}}/build/tests/hash_test
  
  data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run data tests
        run: |

  array:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run array test
        run: |
          chmod +x ${{github.workspace}}/build/tests/array_test
          ${{github.workspace}}/build/tests/array_test
  
  circular_buffer:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run circular buffer test
        run: |
          chmod +x ${{github.workspace}}/build/tests/circular_buffer_test
          ${{github.workspace}}/build/tests/circular_buffer_test

  dict:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run dict test
        run: |
          chmod +x ${{github.workspace}}/build/tests/dict_test
          ${{github.workspace}}/build/tests/dict_test

  queue:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run queue test
        run: |
          chmod +x ${{github.workspace}}/build/tests/queue_test
          ${{github.workspace}}/build/tests/queue_test
    
  stack:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run stack test
        run: |
          chmod +x ${{github.workspace}}/build/tests/stack_test
          ${{github.workspace}}/build/tests/stack_test
  
  binary:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run binary test
        run: |
          chmod +x ${{github.workspace}}/build/tests/binary_test
          ${{github.workspace}}/build/tests/binary_test
  
  tuple:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run tuple test
        run: |
          chmod +x ${{github.workspace}}/build/tests/tuple_test
          ${{github.workspace}}/build/tests/tuple_test
  
  reflection:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run reflection tests
        run: |

  base64:
    needs: reflection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run base64 test
        run: |
          chmod +x ${{github.workspace}}/build/tests/base64_test
          ${{github.workspace}}/build/tests/base64_test
  
  json:
    needs: reflection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run json test
        run: |
          chmod +x ${{github.workspace}}/build/tests/json_test
          ${{github.workspace}}/build/tests/json_test 
          