jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make

  core:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run core examples
        run: |
          ${{github.workspace}}/build/examples/hash_example
          ${{github.workspace}}/build/examples/log_example
          ${{github.workspace}}/build/examples/pack_example
          ${{github.workspace}}/build/examples/sync_example

  data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run data examples
        run: |
          ${{github.workspace}}/build/examples/array_example
          ${{github.workspace}}/build/examples/circular_buffer_example
          ${{github.workspace}}/build/examples/dict_example
          ${{github.workspace}}/build/examples/priority_queue_example
          ${{github.workspace}}/build/examples/queue_example
          ${{github.workspace}}/build/examples/stack_example
          ${{github.workspace}}/build/examples/tree_example
          ${{github.workspace}}/build/examples/tuple_example

  reflection:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run reflection examples
        run: |
          ${{github.workspace}}/build/examples/pack_example
          ${{github.workspace}}/build/examples/json_example ${{github.workspace}}/resources/reflection/json_example_1.json
          ${{github.workspace}}/build/examples/base64_example