name: utilities

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang 
        run: |
          sudo apt install -y wget gnupg software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: make
        run: |
          make CC=clang-20
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  core:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run core tests
        run: |

  sha256_hash:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run sha256_hash
        run: |
          chmod +x ${{github.workspace}}/build/utilities/sha256_hash
          ${{github.workspace}}/build/utilities/sha256_hash < ${{github.workspace}}/include/test/hegel_logic.txt

  rsa_key_generator:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run rsa_key_generator
        run: |
          chmod +x ${{github.workspace}}/build/utilities/rsa_key_generator
          ${{github.workspace}}/build/utilities/rsa_key_generator

  lisp_syntax_highlighter:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run lisp_syntax_highlighter
        run: |
          chmod +x ${{github.workspace}}/build/utilities/lisp_syntax_highlighter
          ${{github.workspace}}/build/utilities/lisp_syntax_highlighter < ${{github.workspace}}/resources/utilities/sum.lsp

  # data:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run data tests
  #       run: |

  # reflection:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run reflection tests
  #       run: |
