name: examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  core:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run core examples
        run: |

  data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run data examples
        run: |
          ${{github.workspace}}/build/examples/array_example
          ${{github.workspace}}/build/examples/circular_buffer_example
          ${{github.workspace}}/build/examples/dict_example
          ${{github.workspace}}/build/examples/priority_queue_example
          ${{github.workspace}}/build/examples/queue_example
          ${{github.workspace}}/build/examples/stack_example
          ${{github.workspace}}/build/examples/tree_example
          ${{github.workspace}}/build/examples/tuple_example

  reflection:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run reflection examples
        run: |
          ${{github.workspace}}/build/examples/json_example ${{github.workspace}}/resources/reflection/json_example_1.json
          ${{github.workspace}}/build/examples/base64_example

  log:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Run log example
        run: |
          ./build/examples/log_example
  hash:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hash example
        run: |
          ${{github.workspace}}/build/examples/hash_example
  
  pack:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pack example
        run: |
          ls
          ${{github.workspace}}/build/examples/pack_example
  
  sync:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sync example
        run: |
          ${{github.workspace}}/build/examples/sync_example
